### ISSUE TITLE
build folders

### ISSUE THREAD

**Issue by ronanyeah** [coStars/iLearn#2]
you have all the development files in assets and are also building to the same. a better structure would be to have a folder called `src` for the development files and build them to a folder called `public`. an `assets` folder is usually used for stuff like images, fonts etc, which would be also under public.
for example:
```
src/
  index.js
public/
  js/
    bundle.js
  assets/
    favicon.ico
```

**Comment by Alaa-Khattab** [comment]
We modified the structure files
