### ISSUE TITLE
styling in jsx file

### ISSUE THREAD

**Issue by ronanyeah** [coStars/iLearn#27]
to tidy the code i recommend moving the styles into your css file, and change the CLASSES in your react component (based on the input length logic etc) to change the styles
https://github.com/coStars/iLearn/blob/master/src/Main.jsx#L12
hint: classes in react use the attribute `className`

**Comment by Alaa-Khattab** [comment]
we solve it :)
https://github.com/coStars/iLearn/blob/master/src/LearnForm.jsx#L8
https://github.com/coStars/iLearn/blob/master/public/css/style.css#L45
