### ISSUE TITLE
learn form is importing the store

### ISSUE THREAD

**Issue by ronanyeah** [coStars/iLearn#32]
https://github.com/coStars/iLearn/blob/master/src/LearnForm.jsx#L3

learn form should be getting the actions from its parent component.

**Comment by Alaa-Khattab** [comment]
we try to pass the store as props for learn form component
https://github.com/coStars/iLearn/blob/master/src/index.jsx#L10
https://github.com/coStars/iLearn/blob/master/src/LearnForm.jsx#L18
