### ISSUE TITLE
Use an arrow function in map

### ISSUE THREAD

**Issue by mantagen** [coStars/iLearn#43]
https://github.com/coStars/iLearn/blob/master/src/LearnList.jsx#L6

**Comment by mantagen** [comment]
Why closing issue?

**Comment by AkramBadah** [comment]
https://github.com/coStars/iLearn/blob/master/src/LearnList.jsx#L6

**Comment by mantagen** [comment]
@AkramBadah  It's actually at https://github.com/coStars/iLearn/blob/repoissues/src/LearnList.jsx
(you've linked the wrong branch)
But I can see it :)
