### ISSUE TITLE
Console.log

### ISSUE THREAD

**Issue by mantagen** [coStars/iLearn#46]
https://github.com/coStars/iLearn/blob/master/src/LearnForm.jsx#L19

User ain't gonna see that

**Comment by mantagen** [comment]
https://github.com/coStars/iLearn/blob/master/src/reducer.js#L10

No point leaving these in...

**Comment by ibraghada** [comment]
Fixed, and instead sent an alert
https://github.com/coStars/iLearn/blob/master/src/LearnForm.jsx#L19 

https://github.com/coStars/iLearn/blob/master/src/reducer.js#L10

**Comment by mantagen** [comment]
That is better if you want to inform the user :)

Another thing to consider, would be some text which appears next to the button etc, rather than a popup which the user _must_ interact with.

But sure, this works!
