### ISSUE TITLE
It would be nice if TECH and DOC validated separately

### ISSUE THREAD

**Issue by mantagen** [coStars/iLearn#47]
https://github.com/coStars/iLearn/blob/master/src/LearnForm.jsx#L30-L36

At the moment, everything validates at once, but it would be easy && nice UX if TECH went green, and DOC went green independently, and SUBMIT went green when all inputs are valid.

**Comment by ibraghada** [comment]
https://github.com/coStars/iLearn/blob/master/src/LearnForm.jsx#L36-#L41
