### ISSUE TITLE
`valid-button` should not be an id

### ISSUE THREAD

**Issue by mantagen** [coStars/iLearn#48]
https://github.com/coStars/iLearn/blob/master/src/LearnForm.jsx#L49

If anything it should be a class.

[This is a commonly used module for joining classnames together.](https://github.com/JedWatson/classnames)

**Comment by mohanagy** [comment]
[fixed](https://github.com/coStars/iLearn/commit/e2586ccc0f872982a9242c7a0e8a6ee934741929)
