### ISSUE TITLE
What are these ids doing?

### ISSUE THREAD

**Issue by mantagen** [coStars/iLearn#49]
https://github.com/coStars/iLearn/blob/master/src/LearnForm.jsx#L42
https://github.com/coStars/iLearn/blob/master/src/LearnForm.jsx#L46

1. They're not referenced anywhere
2. Think carefully about when you use ids. They must be unique on a page:
  https://www.w3.org/TR/WCAG20-TECHS/H93.html

**Comment by ibraghada** [comment]
Removed
https://github.com/coStars/iLearn/blob/master/src/LearnForm.jsx#L51

**Comment by mantagen** [comment]
Ace
