### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by mantagen** [coStars/iLearn#50]
![image](https://cloud.githubusercontent.com/assets/12934669/24979264/70a05ade-1fcb-11e7-80ee-65bdb1a4aab1.png)

TO FIX: Use [this responsive meta tag](https://css-tricks.com/snippets/html/responsive-meta-tag/)

![image](https://cloud.githubusercontent.com/assets/12934669/24979279/7c206eee-1fcb-11e7-9a4b-e1ae55884480.png)

TO FIX: Use [media queries](https://zellwk.com/blog/how-to-write-mobile-first-css/) && [develop mobile first](https://www.mightyminnow.com/2013/11/what-is-mobile-first-css-and-why-does-it-rock/)

**Comment by mohanagy** [comment]
[fixed](https://github.com/coStars/iLearn/commit/ca04203b941064212413ff117c757a11c796d73f)

**Comment by mantagen** [comment]
LOVELY
