### ISSUE TITLE
Lines too long

### ISSUE THREAD

**Issue by mantagen** [coStars/iLearn#53]
https://github.com/coStars/iLearn/blob/master/src/LearnForm.jsx#L42

Consider this: http://eslint.org/docs/rules/max-len

**Comment by ibraghada** [comment]
added the eslint max-length rule and fixed the issue
https://github.com/coStars/iLearn/blob/master/src/LearnForm.jsx#L42-L62

**Comment by mantagen** [comment]
lines 49 and 59 still seem to have bad indentation?

**Comment by Alaa-Khattab** [comment]
https://github.com/coStars/iLearn/blob/master/src/LearnForm.jsx#L59

**Comment by mantagen** [comment]
https://github.com/coStars/iLearn/blob/master/src/LearnForm.jsx#L58-L62

Almost there! Props on new lines should be indented

**Comment by Alaa-Khattab** [comment]
https://github.com/coStars/iLearn/blob/master/src/UpdateForm.jsx#L58-L62
