### ISSUE TITLE
Choose a consistent way to declare a function with no params used... 

### ISSUE THREAD

**Issue by mantagen** [coStars/iLearn#54]
https://github.com/coStars/iLearn/blob/master/src/LearnList.jsx#L28

`() => //fn`
vs
`_ => //fn`

http://stackoverflow.com/questions/41085189/using-underscore-variable-with-arrow-functions-in-es6-typescript#answer-41085908

**Comment by AkramBadah** [comment]
modified and used 
() => //fn
https://github.com/coStars/iLearn/blob/master/src/LearnList.jsx#L22

**Comment by mantagen** [comment]
cool
