### ISSUE TITLE
When creating react elements iteratively, remember to use a unique "key" prop

### ISSUE THREAD

**Issue by mantagen** [coStars/iLearn#56]
![image](https://cloud.githubusercontent.com/assets/12934669/24981742/e912edba-1fd5-11e7-8ded-a7ffb5986f55.png)

https://facebook.github.io/react/docs/lists-and-keys.html#keys

**Comment by mohanagy** [comment]
[fixed](https://github.com/coStars/iLearn/commit/118fc821c3002a7e114bc9e6784a8875cc8915b7)
