### ISSUE TITLE
More tests.

### ISSUE THREAD

**Issue by ronanyeah** [coStars/iLearn#63]
Add at least one enzyme test for a component.

Also index.test.js is testing reducers so call it the same name as the file it is testing and place it in the same folder. eg `reducer.test.js`

**Comment by Alaa-Khattab** [comment]
This test for reducer : 
https://github.com/coStars/iLearn/blob/master/tests/reducer.test.js

This test for component using enzyme (just one test)
https://github.com/coStars/iLearn/blob/master/tests/learnForm.test.jsx

**Comment by ronanyeah** [comment]
Very nice :+1:
